# Multi-arch image from prebuilt static binaries (used by the release workflow).
#
# Expects the build context to contain:
#   linux/amd64/tunnel-client
#   linux/arm64/tunnel-client
#   linux/arm/v7/tunnel-client
FROM scratch
ARG TARGETPLATFORM
COPY --chmod=0755 ${TARGETPLATFORM}/tunnel-client /tunnel-client
USER 65534:65534
ENTRYPOINT ["/tunnel-client"]
